/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.RestaurantSupervisor;

import Model.Consumer.CommodityOrder;
import Model.DB4OUtil.DB4OUtil;
import Model.Business.EcoSystem;
import Model.Employee.Employee;
import Model.Enterprise.Enterprise;
import Model.Enterprise.Commodity;
import Model.Enterprise.Restaurant.Menu;
import Model.Enterprise.Restaurant.Restaurant;
import Model.Enterprise.Restaurant.Restaurant.RestaurantCategory;
import Model.Network.Network;
import Model.Organization.Organization;
import Model.UserAccount.EmployeeAccount;
import Model.UserAccount.UserAccount;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author rutu
 */
public class RestaurantSupervisorMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RestaurantSupervisorMainJPanel
     */
    
    
    private EcoSystem system;
    private JPanel container;
    private Network network;
    private Enterprise enterprise;
    private EmployeeAccount employeeAccount;
    private Restaurant restaurant;
    private JFrame frame;
    //private Role accessRole;
    private String path;
    private String originPath;
    //private OrderRequest selectedOrder = null;
    private Employee employee;
    
    public RestaurantSupervisorMainJPanel(EcoSystem system, JPanel container, Network network, Enterprise enterprise,
            UserAccount userAccount, JFrame frame) {
        initComponents();
        this.system = system;
        this.container = container;
        this.network = network;
        this.enterprise = enterprise;
        this.employeeAccount = (EmployeeAccount) userAccount;
        this.frame = frame;
        //this.accessRole = accessRole;
        this.restaurant = (Restaurant) enterprise;
        this.originPath = this.restaurant.getPath();
        this.path = this.restaurant.getPath();
        this.employee = this.employeeAccount.getEmployee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
