/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Consumer;

import Model.Business.EcoSystem;
import Model.Enterprise.Restaurant.Restaurant;
import Model.Enterprise.Outlet.ShopType;
import Model.Enterprise.Mart.Mart;
import Model.Network.Network;
import Model.Role.ConsumerRole;
import Model.UserAccount.ConsumerAccount;
import UserInterface.SignInJFrame;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author risha
 */
public class OutletListJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private JPanel panel;
    private ConsumerAccount consumeracc;
    private Network net;
    private ShopType type;
    private JFrame frame;

    /**
     * Creates new form RestaurantListJPanel
     */
    public OutletListJPanel(EcoSystem system, Network net, JPanel container, ConsumerAccount account, ShopType type, JFrame frame) {
        initComponents();
        this.system = system;
        this.panel = container;
        this.consumeracc = account;
        this.net = net;
        this.type = type;
        this.frame = frame;

        populateTable();
        areaLabel.setText(net.getCity());
        nameLabel.setText(account.getConsumer().getFirstname());
        typeLabel.setText(type.getValue());
    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) OutletTable.getModel();
        dtm.setRowCount(0);
        if (type.equals(ShopType.Restaurant)) {
            for (Restaurant res : net.getRestaurantList()) {
                Object row[] = new Object[2];
                row[0] = res;
                row[1] = res.getCategoryString();
                dtm.addRow(row);
            }
        }
        if (type.equals(ShopType.Mart)) {
            for (Mart mart : net.getStoreList()) {
                Object row[] = new Object[2];
                row[0] = mart;
                row[1] = mart.getCategoryString();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OutletTable = new javax.swing.JTable();
        JPanel = new javax.swing.JPanel();
        restaurantNameLabel = new javax.swing.JLabel();
        detailPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        areaLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        cartButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();

        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 404));

        OutletTable.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        OutletTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OutletTable.setPreferredSize(new java.awt.Dimension(200, 100));
        OutletTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OutletTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(OutletTable);

        JPanel.setPreferredSize(new java.awt.Dimension(655, 498));

        restaurantNameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        restaurantNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        detailPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(restaurantNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(restaurantNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Hello, ");

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        nameLabel.setText("<Name>");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel3.setText("in ");

        areaLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        areaLabel.setText("<Area>");

        logoutButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        logoutButton.setText("SignOut");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        cartButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cartButton.setText("Shopping Basket");
        cartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartButtonActionPerformed(evt);
            }
        });

        profileButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        profileButton.setText("View Profile");
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backButton.setText(" Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        typeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        typeLabel.setText("<Type>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(18, 18, 18)
                        .addComponent(typeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(areaLabel)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel)
                        .addGap(23, 23, 23)
                        .addComponent(logoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cartButton)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton)
                    .addComponent(cartButton)
                    .addComponent(profileButton)
                    .addComponent(backButton)
                    .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OutletTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OutletTableMouseClicked
        int index = OutletTable.getSelectedRow();
        TableModel model = OutletTable.getModel();

        if (index >= 0) {
            if (type.equals(ShopType.Mart)) {
                Mart mart = (Mart) model.getValueAt(index, 0);
                restaurantNameLabel.setText(mart.getOrg_name());
                //ShopDetailsJPanel panel = new ShopDetailsJPanel(this.system, mart, this.consumeracc, net, type);
                detailPanel.remove(this);
                detailPanel.add(panel);
            }
            if (type.equals(ShopType.Restaurant)) {
                Restaurant restaurant = (Restaurant) model.getValueAt(index, 0);
                restaurantNameLabel.setText(restaurant.getOrg_name());
                //ShopDetailsJPanel panel = new ShopDetailsJPanel(this.system, restaurant, this.consumeracc, net, type);
                detailPanel.remove(this);
                detailPanel.add(panel);
            }

            CardLayout layout = (CardLayout) this.detailPanel.getLayout();
            layout.next(detailPanel);
        }
    }//GEN-LAST:event_OutletTableMouseClicked

    private void cartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartButtonActionPerformed
        //CartJFrame frame = new CartJFrame(this.system, this.consumeracc, net);
        frame.setSize(500, 620);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_cartButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        ConsumerProfileJPanel panel = new ConsumerProfileJPanel(this.system, this.panel, this.consumeracc, this.frame, new ConsumerRole());
        this.panel.add(panel);
        CardLayout layout = (CardLayout) this.panel.getLayout();
        layout.next(this.panel);
    }//GEN-LAST:event_profileButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        SignInJFrame lf = new SignInJFrame();
        this.frame.dispose();
        lf.setLocationRelativeTo(null);
        lf.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout layout = (CardLayout) this.panel.getLayout();
        ConsumerMainJPanel cp = new ConsumerMainJPanel(system, panel, this.consumeracc, frame);
        this.panel.add(cp);
        layout.next(this.panel);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JTable OutletTable;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cartButton;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton profileButton;
    private javax.swing.JLabel restaurantNameLabel;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
